config/routes.rb
Rails.application.routes.draw do
  authenticate "admin" do 
    resource 'tweet-engine', :controller => 'tweet_engine/engine', :as => :tweet_engine, :only => [:index] do
      get :search
      post :follow
      get :following
      get :followers
      post :unfollow
      post :stack
      resources :tweet, :except => [:index], :controller => "tweet_engine/tweet"
      resources 'auto-response', :controller => "tweet_engine/auto_response", :as => :auto_response
      resources 'potential-followers', :controller => 'tweet_engine/potential_followers', :as => :potential_followers, :except => [:show]
    end
  
    match '/tweet-engine' => "tweet_engine/engine#index", :as => :tweet_engine
  end
end

app/controllers/tweet_stack_controller.rb
class TweetStackController < ApplicationController
  include ActionView::Helpers::TextHelper
  
  before_filter :tweet_stack
  before_filter :instantiate_stack
  
  def index
    @followers = TweetStack.followers
  end
  
  def search
    @results = TweetStack.search params[:q]
    @term = params[:q]
    render :index
  end
  
  def follow
    @new_followers = []
    params[:followers].each do |screen_name|
      @new_followers << TweetStack.follow(screen_name)
    end
    flash[:notice] = "You are now following #{pluralize(@new_followers.count, "more person")}"
    render :index
  end
  
  def stack
    TweetStack.stack params[:message]
    flash[:notice] = "Added new tweet to the stack"
    redirect_to tweet_stack_path
  end
  
  def following
    @followers = TweetStack.following
  end
  
  def unfollow
    Twitter.unfollow params[:screen_name]
    flash[:notice] = "Unfollowing #{params[:screen_name]}"
    redirect_to tweet_stack_path
  end
  
  private
  def tweet_stack
    @tweet_stack = TweetStack::Stack.all
  end
  
  def instantiate_stack
    @stack = TweetStack::Stack.new
  end
end

app/views/tweet_stack/followers.html.erb
<ul>
  <% @followers.each do |follower| %>
  <li>
    <%= follower %><%= button_to "Unfollow", tweet_stack_unfollow_path(:screen_name => follower)%>
  </li>
  <% end %>
</ul>

app/views/tweet_stack/index.html.erb
<h2>Tweet stack</h2>

<% if notice %> 
  <p id="notice"><%= notice %></p>
<% end %>

Auto-searching for <%= TweetStack.config['keywords'] %><br />
You currently have <%= TweetStack.followers.count %> followers<br />
You are following <%= TweetStack.following.count %> tweeple<br />

Number of found potential users <%= TweetStack::PotentialFollower.all.count %>
<%= link_to "Followers", tweet_stack_following_path %>

<%= form_tag(tweet_search_phrase_path, :method => :get) do |f| %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>


<% if @results.present? %>
  <%= form_tag(tweet_follow_path) do |f| %>
    Tweeple talking about '<%= @term %>':<br />
    <ul>
    <% @results.each_with_index do |tweeple, index| %>
      <li>
        <%= label_tag "followers[name][#{tweeple.from_user}]", tweeple.from_user %><%= check_box_tag "followers[name][#{tweeple.from_user}]", tweeple.from_user %><br />
        <%= tweeple.text %>
      </li>
    <% end %>
    </ul>
    <%= submit_tag("Follow") %>
  <% end %>
<% end %>

<% if @tweet_stack.empty? %>
  No tweets stacked<br />
<% else%>
  Stacked tweets<br />
  <ul>
  <% @tweet_stack.each do |tweet| %>
    <li><%= tweet.message %> - 
      <% if not tweet.delivered %>
      <%= tweet.sending_at.to_s %> - <%= link_to "Edit", edit_tweet_path(:id => tweet.id) %> - 
    <%= link_to "Delete", tweet_path(:id => tweet.id), :method => :delete, :confirm => "Are you sure you want to delete this entry?" %>
      <% else %>
      Sent at <%= tweet.sending_at %>
      <% end %>
    </li>
  <% end %>
  </ul>
<% end %>
<%= simple_form_for @stack, :url => tweet_index_path, :method => :post do |f| %>
  <%= f.input :message, :as => :text, :label => "Enter Tweet" %>
  <%= f.input :sending_at, :input_html => {:class => "datepicker"} %>
  <%= f.submit("Stack Tweet") %>
<% end %>