config/routes.rb
Rails.application.routes.draw do
  authenticate "admin" do 
    resource 'tweet-engine', :controller => 'tweet_engine/engine', :as => :tweet_engine, :only => [:index] do
      get :search
      post :follow
      get :following
      get :followers
      post :unfollow
      post :stack
      resources :tweet, :except => [:index], :controller => "tweet_engine/tweet"
      resources 'auto-response', :controller => "tweet_engine/auto_response", :as => :auto_response
      resources 'potential-followers', :controller => 'tweet_engine/potential_followers', :as => :potential_followers, :except => [:show]
    end
  
    match '/tweet-engine' => "tweet_engine/engine#index", :as => :tweet_engine
  end
end

app/views/shared/_flash_messages.html.erb
  <% if flash[:alert] %>
	<!-- Status Bar Start -->
    <div class="status warning">
    	<p class="closestatus"><a href="" title="Close">x</a></p>
    	<p></img src="/img/icons/icon_warning.png" alt="Warning" /><span>Attention!</span><%= flash[:alert] %></p>
    </div>
    <!-- Status Bar End -->
  <% end %>
    
  <% if flash[:success] %>
   <!-- Red Status Bar Start -->
    <div class="status success">
    	<p class="closestatus"><a href="" title="Close">x</a></p>
    	<p></img src="/img/icons/icon_success.png" alt="Success" /><span>Success!</span><%= flash[:success] %></p>
    </div>
    <!-- Red Status Bar End -->
  <% end %>
    
  <% if flash[:error] %>
    <!-- Green Status Bar Start -->
    <div class="status error">
    	<p class="closestatus"><a href="" title="Close">x</a></p>
    	<p></img src="/img/icons/icon_error.png" alt="Error" /><span>Error!</span><%= flash[:error] %></p>
    </div>
    <!-- Green Status Bar End -->
  <% end %>
  
  <% if flash[:notice] %>
    <!-- Blue Status Bar Start -->
    <div class="status info">
    	<p class="closestatus"><a href="" title="Close">x</a></p>
    	<p></img src="/img/icons/icon_info.png" alt="Information" /><span>Information:</span><%= flash[:notice] %></p>
    </div>
  <!-- Blue Status Bar End -->
  <% end %>

app/views/shared/_search.html.erb
<%= form_tag(search_tweet_engine_path, :method => :get) do |f| %>
  <%= text_field_tag(:q, nil, :class => "searchbox", :placeholder => "Search control panel...") %>
  <%= submit_tag("Search", :class => "searchbtn") %>
<% end %>

app/views/shared/_tweet_form.html.erb
<div class="contentcontainer med left">
 <div class="headings alt">
   <h2>Add a tweet to the stack</h2>
 </div>
 <div class="contentbox">
   <%= form_for stack, :url => tweet_engine_tweet_index_path, :method => :post do |f| %>
    <p>
      <%= f.label :message, "Enter Tweet" %>
      <%= f.text_field :message, :class => "inputbox" %>
    </p>
    <p>
      <%= f.label :repeat, "Repeat" %>
      <%= f.check_box :repeat %>
    </p>
    <p>
      <%= f.label :every, "Every" %>
      <%= f.text_field :every, :class => "inputbox" %>
    </p>
    <p>
      <%= f.label :sending_at, "Sending At" %>
      <%= f.text_field :sending_at, :class =>'datepicker inputbox' %>
    </p>
    <%= f.submit "Stack Tweet", :disable_with => 'Stack Tweeting...', :class => "btn" %>
   <% end %>
 </div>
</div>