config/routes.rb
Rails.application.routes.draw do
  authenticate "admin" do 
    resource 'tweet-engine', :controller => 'tweet_engine/engine', :as => :tweet_engine, :only => [:index] do
      get :search
      post :follow
      get :following
      get :followers
      post :unfollow
      post :stack
      resources :tweet, :except => [:index], :controller => "tweet_engine/tweet"
      resources 'auto-response', :controller => "tweet_engine/auto_response", :as => :auto_response
      resources 'potential-followers', :controller => 'tweet_engine/potential_followers', :as => :potential_followers, :except => [:show]
    end
  
    match '/tweet-engine' => "tweet_engine/engine#index", :as => :tweet_engine
  end
end

app/models/tweet_engine/responder.rb
require 'mongoid'

module TweetEngine
  class Responder
    include Mongoid::Document
    field :key_phrases
    field :response
    field :sent_to, :type => Array, :default => []
    
    validates_presence_of :key_phrases, :response
    validates_length_of :response, :maximum => 140, :message => "must be less than 140 characters"
    
    class << self
      def respond
        @users_reponded_to = []
        auto_responses = self.all.to_a
        search_for_respondees auto_responses
        @users_reponded_to
      end
      
      protected
      
      def search_for_respondees auto_responses
        auto_responses.each do |auto_response|
          tweets = TweetEngine.search auto_response.key_phrases
          send_response tweets, auto_response
        end
      end
      
      def send_response tweets, auto_response
        tweets.each_with_index do |tweet, index|
          unless auto_response.sent_to.include? tweet.from_user
            TweetEngine::Stack.create! :message => "@#{tweet.from_user} #{auto_response.response}", :sending_at => Time.now + (index.to_i.minutes)
            auto_response.sent_to << tweet.from_user
          end
        end
        auto_response.save
        @users_reponded_to.concat auto_response.sent_to
      end
    end
  end
end

app/models/tweet_engine/search_result.rb
require 'mongoid'

module TweetEngine
  class SearchResult
    include Mongoid::Document
    
    field :screen_name
    field :tweet
    
    validates_uniqueness_of :screen_name, :tweet
  end
end

app/models/tweet_engine/stack.rb
require 'mongoid'
require 'delayed_job_mongoid'

module TweetEngine
  class Stack
    
    include Mongoid::Document
    
    field :message
    field :sending_at, :type => Time, :default => Time.now
    field :delivered, :default => false
    field :repeat, :default => false
    field :every
    
    scope :to_deliver, where(:sending_at.lte => Time.now)
    
    after_create :deliver
    
    validates_length_of :message, :maximum => 140, :message => "must be less than 140 characters"
    validates :sending_at, :date => { :after_or_equal_to => Time.now }
    
    def sendable?
      Time.now >= self.sending_at
    end
    
    def deliver
      if self.sendable?
        Twitter.update self.message
        self.update_attribute :delivered, true
        self.delivered
        set_when_repeatable
      end
    end
    
    handle_asynchronously :deliver, :run_at => Proc.new {|p| p.sending_at }
    
    protected
    
    def set_when_repeatable
      if self.repeat
        TweetEngine::Stack.create!(
          :message => self.message,
          :sending_at => (Time.now + eval(self.every.split(' ').join('.'))),
          :repeat => true,
          :every => self.every
         )
      end
    end
  end
end

app/controllers/tweet_engine/auto_response_controller.rb
class TweetEngine::AutoResponseController < TweetEngineController
  
  def index
    @auto_responses = TweetEngine::Responder.all
  end
  
  def new
    @user = TweetEngine.whats_my.user
    @auto_response = TweetEngine::Responder.new
  end
  
  def create
    @auto_response = TweetEngine::Responder.new params[:tweet_engine_responder]
    if @auto_response.save
      flash[:notice] = 'Added new auto-response'
      redirect_to tweet_engine_path
    else
      render :new
    end
  end
  
  def edit
    @auto_response = TweetEngine::Responder.find params[:id]
  end
  
  def update
    @auto_response = TweetEngine::Responder.find params[:id]
    if @auto_response.update_attributes params[:tweet_engine_responder]
      flash[:notice] = 'Updated auto-response'
      redirect_to tweet_engine_path
    else
      render :edit
    end
  end
end

app/controllers/tweet_engine/engine_controller.rb
class TweetEngine::EngineController < TweetEngineController
  
  include ActionView::Helpers::TextHelper
  
  #
  # GET /tweet-engine
  #
  # This is the main dashboard
  #
  def index
    @tweet_stack = TweetEngine::Stack.paginate :page => params[:page], :per_page => 10
    @stack = TweetEngine::Stack.new
    @user = TweetEngine.whats_my.user
  end
  
  #
  # POST /tweet-engine/search
  #
  # Manually search for people to follow
  #
  def search
    @results = TweetEngine.search(params[:q]).paginate :page => params[:page], :per_page => 10
    @term = params[:q]
  end
  
  #
  # POST /tweet-engine/follow
  #
  # Follow selected people
  #
  def follow
    @new_followers = []
    params[:followers].each do |screen_name|
      screen_name = screen_name.last
      @new_followers << TweetEngine.follow(screen_name)
      TweetEngine::SearchResult.delete_all(:conditions => { :screen_name => screen_name })
    end
    flash[:notice] = "You are now following #{pluralize(@new_followers.count, "more person")}"
    redirect_to tweet_engine_path
  end
  
  #
  # GET /tweet-engine/following
  #
  # View people we follow
  #
  # This controller is primarily used to determine whether
  # someone we are following is following us back.
  #
  # @TODO Add more information about the users influence
  #
  def following
    @following = TweetEngine.following
    @following = TweetEngine.following.paginate :per_page => 10, :page => params[:page] unless @following.nil?
  end
  
  #
  # GET /tweet-engine/followers
  #
  # Displays the people that are following us.
  #
  # We can also unfollow people once they follow us.
  #
  # @TODO We should add information about a person to help to decide whether to unfollow someone or not
  #
  def followers
    @followers = TweetEngine.followers.paginate :per_page => 10, :page => params[:page]
  end
  
  # POST /tweet-engine/unfollow
  #
  # Unfollows a a group of people
  #
  # This is generally used when we want to clean up our timeline
  #
  def unfollow
    @unfollowed = []
    params[:unfollow].each do |screen_name|
      @unfollowed << Twitter.unfollow(screen_name.last)
    end
    flash[:notice] = "Unfollowed #{@unfollowed.count} tweeple"
    redirect_to tweet_engine_path
  end
end

app/controllers/tweet_engine/potential_followers_controller.rb
class TweetEngine::PotentialFollowersController < TweetEngineController
  
  #
  # GET /tweet-engine/potential-followers
  #
  # Gathers a list of all the potential followers built up from
  # doing our background searches. Here we can manually follow these users.
  #
  def index
    @potential_followers = TweetEngine::SearchResult.paginate :per_page => 10, :page => params[:page]
  end
  
  def destroy
    @potential_follower = TweetEngine::SearchResult.find params[:id]
    @potential_follower.destroy
    flash[:notice] = "Removed the search result from the stack"
    redirect_to tweet_engine_potential_followers_path
  end
end

app/controllers/tweet_engine/tweet_controller.rb
#
# Controller used to manage our tweet stack
#
class TweetEngine::TweetController < TweetEngineController
  
  def create
    @tweet = TweetEngine::Stack.create params[:tweet_engine_stack]
    flash[:notice] = "Added new tweet to the stack"
    redirect_to tweet_engine_path
  end
  
  def edit
    @tweet = TweetEngine::Stack.find params[:id]
  end
  
  def update
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.update_attributes params[:tweet_engine_stack]
    flash[:notice] = "Updated the tweet"
    redirect_to tweet_engine_path
  end
  
  def destroy
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.destroy
    flash[:notice] = "Removed the tweet from the stack"
    redirect_to tweet_engine_path
  end
end

app/controllers/tweet_engine/tweets_controller.rb
#
# Controller used to manage our tweet stack
#
class TweetEngine::TweetsController < ApplicationController
  
  def create
    @tweet = TweetEngine::Stack.create params[:tweet_engine_stack]
    @tweet.deliver
    flash[:notice] = "Added new tweet to the stack"
    redirect_to tweet_engine_path
  end
  
  def edit
    @stack = TweetEngine::Stack.find params[:id]
  end
  
  def update
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.update_attributes params[:tweet_engine_stack]
    flash[:notice] = "Updated the tweet"
    redirect_to tweet_engine_path
  end
  
  def destroy
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.destroy
    flash[:notice] = "Removed the tweet from the stack"
    redirect_to tweet_engine_path
  end
end

app/controllers/tweet_engine_controller.rb
class TweetEngineController < ApplicationController
  before_filter :find_user
  before_filter :find_search_results
  
  layout 'tweet_engine'
  
  protected
  
  def find_user
    @user = TweetEngine.whats_my.user
  end
  
  def find_search_results
    @latest_search_results = TweetEngine::SearchResult.paginate :per_page => 5, :page => 1
  end
  
end

app/views/tweet_engine/engine/_notices.html.erb
<!-- Content Box Start -->
<div class="contentcontainer sml right">
  <div class="headings">
      <h2>Notices</h2>
  </div>
  <div class="contentbox">
    <% if TweetEngine.config['search'] %>
      <div class="noticebox">
        <div class="innernotice">
          <h4>Search information</h4>
          <p>Auto-searching for <%= TweetEngine.config['keywords'] %></p>
          <p>You currently have <%= TweetEngine.whats_my.user.followers_count %> <%= link_to "followers", followers_tweet_engine_path %></p>
          <p>You are <%= link_to "following", following_tweet_engine_path %> <%= @user.friends_count %> tweeple</p>
          <p>Number of found <%= link_to "potential followers", tweet_engine_potential_followers_path %> <%= TweetEngine::SearchResult.all.count %></p>
        </div>
      </div>
     <% end %>
      <div class="noticeboxalt">
        <div class="innernotice">
          <h4>Tweet Info</h4>
          <p>Your account was created <%= time_ago_in_words @user.created_at %></p>
          <p>Your last tweet was @ <%= distance_of_time_in_words Time.now, @user.status.created_at%>: <%= @user.status.text %></p>
          </div>
      </div>
      <div style="clear: both;"></div>
  </div>
</div>
<!-- Content Box End -->

app/views/tweet_engine/engine/_stack.html.erb
<% if tweet_stack.empty? %>
    No tweets stacked<br />
<% else%>
<!-- TweetStack Content Box Start -->
<div class="contentcontainer">
  
  <div class="headings altheading">
    <h2>Stacked Tweets</h2>
  </div>
  <div class="contentbox">
  	<table width="100%">
    	<thead>
        <tr>
          <th>Sending @</th>
          <th>Tweet</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% tweet_stack.each do |tweet| %>
      	<tr>
          <td>
        	 <% if not tweet.delivered %>
            Sending in <%= time_ago_in_words tweet.sending_at %>
            <% if tweet.repeat %>
              this will be repeated every <%= tweet.every.to_s %>
             <% end %>
            <% else %>
              this was sent at <%= time_ago_in_words tweet.sending_at %>
            <% end %>
        	</td>
          <td><%= tweet.message %></td>
          <td>
            <%= link_to raw('<img src="/img/icons/icon_edit.png" alt="Edit" />'), edit_tweet_engine_tweet_path(:id => tweet.id) %>
            <%= link_to raw('<img src="/img/icons/icon_delete.png" alt="Delete" />'), tweet_engine_tweet_path(:id => tweet.id), :method => :delete, :confirm => "Are you sure you want to delete this entry?" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
      <div class="extrabottom">
      	<ul>
        	<li><img src="/img/icons/icon_edit.png" alt="Edit" /> Edit</li>
          <li><img src="/img/icons/icon_delete.png" alt="Delete" /> Remove</li>
        </ul>
      </div>
      <%= will_paginate @tweet_stack %>
  </div>
</div>
<!-- TweetStack Content Box End -->
<% end %>

app/views/tweet_engine/engine/followers.html.erb
<!-- TweetStack Content Box Start -->
<div class="contentcontainer">
  
  <div class="headings altheading">
    <h2>People following us</h2>
  </div>
  <div class="contentbox">
    <%= form_tag(:action => "unfollow") do %>
  	<table width="100%">
    	<thead>
        <tr>
          <th>Screen name</th>
          <th>Description</th>
          <th>Followers</th>
          <th>Following</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @followers.each_with_index do |user,index| %>
      	<tr>
          <td><%= user.screen_name %></td>
          <td><%= user.description %></td>
          <td><%= user.followers_count %></td>
          <td><%= user.friends_count %></td>
          <td>
            <% if user.following %>
              <%= check_box_tag "unfollow[#{index}]", user.screen_name %>
            <% else %>
            &nbsp;
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
      <div class="extrabottom">
          <div class="bulkactions">
            <%= submit_tag "Unfollow tweeple", :disable_with => 'Unfollowing tweeple...', :class => "btn" %>
          </div>
      </div>
    <% end %>
    <%= will_paginate @followers %>
  </div>
</div>
<!-- TweetStack Content Box End -->

app/views/tweet_engine/engine/following.html.erb
<!-- TweetStack Content Box Start -->
<div class="contentcontainer">
  
  <div class="headings altheading">
    <h2>People following</h2>
  </div>
  <div class="contentbox">
    <%= form_tag(:action => "unfollow") do %>
  	<table width="100%">
    	<thead>
        <tr>
          <th>Screen name</th>
          <th>Description</th>
          <th>Followers</th>
          <th>Following</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @following.each_with_index do |user,index| %>
      	<tr>
          <td><%= user.screen_name %></td>
          <td><%= user.description %></td>
          <td><%= user.followers_count %></td>
          <td><%= user.friends_count %></td>
          <td>
            <% if user.following %>
              <%= check_box_tag "unfollow[#{index}]", user.screen_name %>
            <% else %>
            &nbsp;
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
      <div class="extrabottom">
          <div class="bulkactions">
            <%= submit_tag "Unfollow tweeple", :disable_with => 'Unfollowing tweeple...', :class => "btn" %>
          </div>
      </div>
    <% end %>
    <%= will_paginate @following %>
  </div>
</div>
<!-- TweetStack Content Box End -->

app/views/tweet_engine/engine/index.html.erb
<%= render :partial => 'shared/tweet_form', :locals => {:stack => @stack} %>
    
<%= render :partial => 'notices' %>

<div style="clear: both;"></div>
<%= render :partial => "stack", :locals => {:tweet_stack => @tweet_stack}%>

app/views/tweet_engine/engine/potential_followers.html.erb
<% unless @potential_followers.empty? %>

<!-- TweetStack Content Box Start -->
<div class="contentcontainer">
  
  <div class="headings altheading">
    <h2>Potential Followers</h2>
  </div>
  <div class="contentbox">
    <%= form_tag(:action => "follow") do %>
  	<table width="100%">
    	<thead>
        <tr>
          <th>Screen name</th>
          <th>Tweet</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @potential_followers.each_with_index do |user,index| %>
      	<tr>
          <td><%= user.screen_name %></td>
          <td><%= user.tweet['text'] %></td>
          <td><%= check_box_tag "followers[#{index}]", user.screen_name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
      <div class="extrabottom">
          <div class="bulkactions">
            <%= submit_tag "Follow tweeple", :disable_with => 'Follow tweeple...' %>
          </div>
      </div>
    <% end %>
    <%= will_paginate @potential_followers %>
  </div>
</div>
<!-- TweetStack Content Box End -->
<% end %>

app/views/tweet_engine/engine/search.html.erb
<% if @results.present? %>
<!-- TweetStack Content Box Start -->
<div class="contentcontainer">
  
  <div class="headings altheading">
    <h2>Tweeple talking about '<%= @term %>'</h2>
  </div>
  <div class="contentbox">
    <%= form_tag(:action => "follow") do %>
  	<table width="100%">
    	<thead>
        <tr>
          <th>Screen name</th>
          <th>Tweet</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each_with_index do |user,index| %>
      	<tr>
          <td><%= user.from_user %></td>
          <td><%= user.text %></td>
          <td><%= check_box_tag "followers[#{index}]", user.from_user %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
      <div class="extrabottom">
          <div class="bulkactions">
            <%= submit_tag "Follow tweeple", :disable_with => 'Follow tweeple...', :class => 'btn' %>
          </div>
      </div>
    <% end %>
    <%= will_paginate @results %>
  </div>
</div>
<!-- TweetStack Content Box End -->
<% else %>
<div class="contentcontainer">
  
  <div class="headings altheading">
    <h2>No Search results found</h2>
  </div>
</div>
<% end %>