config/routes.rb
Rails.application.routes.draw do
  authenticate "admin" do 
    resource 'tweet-engine', :controller => 'tweet_engine/engine', :as => :tweet_engine, :only => [:index] do
      get :search
      post :follow
      get :following
      get :followers
      post :unfollow
      post :stack
      resources :tweet, :except => [:index], :controller => "tweet_engine/tweet"
      resources 'auto-response', :controller => "tweet_engine/auto_response", :as => :auto_response
      resources 'potential-followers', :controller => 'tweet_engine/potential_followers', :as => :potential_followers, :except => [:show]
    end
  
    match '/tweet-engine' => "tweet_engine/engine#index", :as => :tweet_engine
  end
end

app/models/tweet_engine/responder.rb
require 'mongoid'

module TweetEngine
  class Responder
    include Mongoid::Document
    field :key_phrases
    field :response
    field :sent_to, :type => Array, :default => []
    
    validates_presence_of :key_phrases, :response
    validates_length_of :response, :maximum => 140, :message => "must be less than 140 characters"
    
    class << self
      def respond
        @users_reponded_to = []
        auto_responses = self.all.to_a
        search_for_respondees auto_responses
        @users_reponded_to
      end
      
      protected
      
      def search_for_respondees auto_responses
        auto_responses.each do |auto_response|
          tweets = TweetEngine.search auto_response.key_phrases
          send_response tweets, auto_response
        end
      end
      
      def send_response tweets, auto_response
        tweets.each_with_index do |tweet, index|
          unless auto_response.sent_to.include? tweet.from_user
            TweetEngine::Stack.create! :message => "@#{tweet.from_user} #{auto_response.response}", :sending_at => Time.now + (index.to_i.minutes)
            auto_response.sent_to << tweet.from_user
          end
        end
        auto_response.save
        @users_reponded_to.concat auto_response.sent_to
      end
    end
  end
end

app/models/tweet_engine/search_result.rb
require 'mongoid'

module TweetEngine
  class SearchResult
    include Mongoid::Document
    
    field :screen_name
    field :tweet
    
    validates_uniqueness_of :screen_name, :tweet
  end
end

app/models/tweet_engine/stack.rb
require 'mongoid'
require 'delayed_job_mongoid'

module TweetEngine
  class Stack
    
    include Mongoid::Document
    
    field :message
    field :sending_at, :type => Time, :default => Time.now
    field :delivered, :default => false
    field :repeat, :default => false
    field :every
    
    scope :to_deliver, where(:sending_at.lte => Time.now)
    
    after_create :deliver
    
    validates_length_of :message, :maximum => 140, :message => "must be less than 140 characters"
    validates :sending_at, :date => { :after_or_equal_to => Time.now }
    
    def sendable?
      Time.now >= self.sending_at
    end
    
    def deliver
      if self.sendable?
        Twitter.update self.message
        self.update_attribute :delivered, true
        self.delivered
        set_when_repeatable
      end
    end
    
    handle_asynchronously :deliver, :run_at => Proc.new {|p| p.sending_at }
    
    protected
    
    def set_when_repeatable
      if self.repeat
        TweetEngine::Stack.create!(
          :message => self.message,
          :sending_at => (Time.now + eval(self.every.split(' ').join('.'))),
          :repeat => true,
          :every => self.every
         )
      end
    end
  end
end

app/controllers/tweet_engine/auto_response_controller.rb
class TweetEngine::AutoResponseController < TweetEngineController
  
  def index
    @auto_responses = TweetEngine::Responder.all
  end
  
  def new
    @user = TweetEngine.whats_my.user
    @auto_response = TweetEngine::Responder.new
  end
  
  def create
    @auto_response = TweetEngine::Responder.new params[:tweet_engine_responder]
    if @auto_response.save
      flash[:notice] = 'Added new auto-response'
      redirect_to tweet_engine_path
    else
      render :new
    end
  end
  
  def edit
    @auto_response = TweetEngine::Responder.find params[:id]
  end
  
  def update
    @auto_response = TweetEngine::Responder.find params[:id]
    if @auto_response.update_attributes params[:tweet_engine_responder]
      flash[:notice] = 'Updated auto-response'
      redirect_to tweet_engine_path
    else
      render :edit
    end
  end
end

app/controllers/tweet_engine/engine_controller.rb
class TweetEngine::EngineController < TweetEngineController
  
  include ActionView::Helpers::TextHelper
  
  #
  # GET /tweet-engine
  #
  # This is the main dashboard
  #
  def index
    @tweet_stack = TweetEngine::Stack.paginate :page => params[:page], :per_page => 10
    @stack = TweetEngine::Stack.new
    @user = TweetEngine.whats_my.user
  end
  
  #
  # POST /tweet-engine/search
  #
  # Manually search for people to follow
  #
  def search
    @results = TweetEngine.search(params[:q]).paginate :page => params[:page], :per_page => 10
    @term = params[:q]
  end
  
  #
  # POST /tweet-engine/follow
  #
  # Follow selected people
  #
  def follow
    @new_followers = []
    params[:followers].each do |screen_name|
      screen_name = screen_name.last
      @new_followers << TweetEngine.follow(screen_name)
      TweetEngine::SearchResult.delete_all(:conditions => { :screen_name => screen_name })
    end
    flash[:notice] = "You are now following #{pluralize(@new_followers.count, "more person")}"
    redirect_to tweet_engine_path
  end
  
  #
  # GET /tweet-engine/following
  #
  # View people we follow
  #
  # This controller is primarily used to determine whether
  # someone we are following is following us back.
  #
  # @TODO Add more information about the users influence
  #
  def following
    @following = TweetEngine.following
    @following = TweetEngine.following.paginate :per_page => 10, :page => params[:page] unless @following.nil?
  end
  
  #
  # GET /tweet-engine/followers
  #
  # Displays the people that are following us.
  #
  # We can also unfollow people once they follow us.
  #
  # @TODO We should add information about a person to help to decide whether to unfollow someone or not
  #
  def followers
    @followers = TweetEngine.followers.paginate :per_page => 10, :page => params[:page]
  end
  
  # POST /tweet-engine/unfollow
  #
  # Unfollows a a group of people
  #
  # This is generally used when we want to clean up our timeline
  #
  def unfollow
    @unfollowed = []
    params[:unfollow].each do |screen_name|
      @unfollowed << Twitter.unfollow(screen_name.last)
    end
    flash[:notice] = "Unfollowed #{@unfollowed.count} tweeple"
    redirect_to tweet_engine_path
  end
end

app/controllers/tweet_engine/potential_followers_controller.rb
class TweetEngine::PotentialFollowersController < TweetEngineController
  
  #
  # GET /tweet-engine/potential-followers
  #
  # Gathers a list of all the potential followers built up from
  # doing our background searches. Here we can manually follow these users.
  #
  def index
    @potential_followers = TweetEngine::SearchResult.paginate :per_page => 10, :page => params[:page]
  end
  
  def destroy
    @potential_follower = TweetEngine::SearchResult.find params[:id]
    @potential_follower.destroy
    flash[:notice] = "Removed the search result from the stack"
    redirect_to tweet_engine_potential_followers_path
  end
end

app/controllers/tweet_engine/tweet_controller.rb
#
# Controller used to manage our tweet stack
#
class TweetEngine::TweetController < TweetEngineController
  
  def create
    @tweet = TweetEngine::Stack.create params[:tweet_engine_stack]
    flash[:notice] = "Added new tweet to the stack"
    redirect_to tweet_engine_path
  end
  
  def edit
    @tweet = TweetEngine::Stack.find params[:id]
  end
  
  def update
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.update_attributes params[:tweet_engine_stack]
    flash[:notice] = "Updated the tweet"
    redirect_to tweet_engine_path
  end
  
  def destroy
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.destroy
    flash[:notice] = "Removed the tweet from the stack"
    redirect_to tweet_engine_path
  end
end

app/controllers/tweet_engine/tweets_controller.rb
#
# Controller used to manage our tweet stack
#
class TweetEngine::TweetsController < ApplicationController
  
  def create
    @tweet = TweetEngine::Stack.create params[:tweet_engine_stack]
    @tweet.deliver
    flash[:notice] = "Added new tweet to the stack"
    redirect_to tweet_engine_path
  end
  
  def edit
    @stack = TweetEngine::Stack.find params[:id]
  end
  
  def update
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.update_attributes params[:tweet_engine_stack]
    flash[:notice] = "Updated the tweet"
    redirect_to tweet_engine_path
  end
  
  def destroy
    @tweet = TweetEngine::Stack.find params[:id]
    @tweet.destroy
    flash[:notice] = "Removed the tweet from the stack"
    redirect_to tweet_engine_path
  end
end

app/controllers/tweet_engine_controller.rb
class TweetEngineController < ApplicationController
  before_filter :find_user
  before_filter :find_search_results
  
  layout 'tweet_engine'
  
  protected
  
  def find_user
    @user = TweetEngine.whats_my.user
  end
  
  def find_search_results
    @latest_search_results = TweetEngine::SearchResult.paginate :per_page => 5, :page => 1
  end
  
end

app/views/tweet_engine/index.html.erb
<p>
  Hi <%= TweetEngine.whats_my.user.screen_name %>, this is your TweetEngine.<br/>
  Your account was created at: <%= TweetEngine.whats_my.user.created_at %>
</p>

<div id="tweet-stats">
<% if TweetEngine.config['search'] %>
  <p>
    Auto-searching for <%= TweetEngine.config['keywords'] %>
  </p>
<% end %>
  
  <p>
    You currently have <%= TweetEngine.whats_my.user.followers_count %> <%= link_to "followers", tweet_engine_followers_path %><br />
    You are <%= link_to "following", tweet_engine_following_path %> <%= TweetEngine.whats_my.user.friends_count %> tweeple<br />
  </p>
  
  <p>Your last tweet was: <%= TweetEngine.whats_my.user.status.text %> @ <%= TweetEngine.whats_my.user.status.created_at%></p>
  
  Number of found <%= link_to "potential followers", tweet_engine_potential_followers_path %> <%= TweetEngine::SearchResult.all.count %><br/>
</div>

<div id="tweet-engine-search">
  <div class="search">
    <%= form_tag(tweet_search_phrase_path, :method => :get) do |f| %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>

  <div class="results">
    <% if @results.present? %>
      <%= form_tag(tweet_follow_path) do |f| %>
        Tweeple talking about '<%= @term %>':<br />
        <ul>
        <% @results.each_with_index do |tweeple, index| %>
          <li>
            <%= label_tag "followers[#{index}]", tweeple.from_user %><%= check_box_tag "followers[#{index}]", tweeple.from_user %><br />
            <%= tweeple.text %>
          </li>
        <% end %>
        </ul>
        <%= submit_tag("Follow") %>
      <% end %>
    <% end %>
  </div>
</div>

<div id="tweet-stack">
<% if @tweet_stack.empty? %>
    No tweets stacked<br />
<% else%>
  <h3>Stacked tweets</h3>
  <ul>
  <% @tweet_stack.each do |tweet| %>
    <li><%= tweet.message %> - 
      <% if not tweet.delivered %>
      <%= tweet.sending_at.to_s %> - <%= link_to "Edit", edit_tweet_path(:id => tweet.id) %> - 
    <%= link_to "Cancel", tweet_path(:id => tweet.id), :method => :delete, :confirm => "Are you sure you want to delete this entry?" %>
      <% else %>
      Sent at <%= tweet.sending_at %>
      <% end %>
    </li>
  <% end %>
  </ul>
<% end %>
</div>

<div id="schedule-tweet">
  <%= form_for @stack, :url => tweet_index_path, :method => :post do |f| %>
    <p><%= f.label :message, "Enter Tweet" %>
    <%= f.text_field :message %></p>
    <p><%= f.label :sending_at, "Sending At" %>
    <%= f.text_field :sending_at, :class =>'datepicker' %>
    </p>
    <%= f.submit "Stack Tweet", :disable_with => 'Stack Tweeting...' %>
  <% end %>
</div>